# Generated by Django 4.1 on 2024-06-10 02:02

from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car5adam',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('is_deleted_Car5adam', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id_car_type', models.AutoField(primary_key=True, serialize=False)),
                ('name_car_type', models.CharField(max_length=255)),
                ('Kerya_prix_car_type', models.FloatField()),
                ('Tewsila_prix_car_type', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_deleted_p', models.BooleanField(default=False)),
                ('phone_number_p', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Salahiyat',
            fields=[
                ('id_salahiya', models.AutoField(primary_key=True, serialize=False)),
                ('name_salahiya', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_person', serialize=False, to='API.person')),
                ('id_super', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_super', to='API.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id_employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.person')),
                ('driving_license', models.IntegerField(unique=True)),
                ('ta9yim_employer', models.FloatField()),
                ('is_allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tewsila',
            fields=[
                ('id_Tewsila', models.AutoField(primary_key=True, serialize=False)),
                ('t_started', models.TimeField()),
                ('t_ended', models.TimeField()),
                ('from_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('to_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('comment_Tewsila', models.TextField()),
                ('ta9yim_Tewsila', models.FloatField()),
                ('id_car_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.car5adam')),
                ('id_zaboun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.person')),
            ],
        ),
        migrations.CreateModel(
            name='Kerya',
            fields=[
                ('id_Kerya', models.AutoField(primary_key=True, serialize=False)),
                ('t_started', models.TimeField()),
                ('t_ended', models.TimeField()),
                ('comment_Kerya', models.TextField()),
                ('ta9yim_Kerya', models.FloatField()),
                ('id_car_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.car5adam')),
                ('id_zaboun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.person')),
            ],
        ),
        migrations.AddField(
            model_name='car5adam',
            name='id_type_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.cartype'),
        ),
        migrations.CreateModel(
            name='GetPayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employer')),
            ],
        ),
        migrations.AddField(
            model_name='car5adam',
            name='id_employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employer'),
        ),
        migrations.CreateModel(
            name='AdminSalahiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_salahiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.salahiyat')),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.admin')),
            ],
        ),
    ]
