# Generated by Django 4.1 on 2024-06-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kerya',
            old_name='id_car_employer',
            new_name='matricule_car',
        ),
    ]
