# Generated by Django 4.1 on 2024-06-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_id_car_employer_kerya_matricule_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='car_poitds',
            field=models.IntegerField(default=100),
        ),
    ]
