# Generated by Django 4.1 on 2024-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_cartype_car_poitds'),
    ]

    operations = [
        migrations.AddField(
            model_name='caremployer',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
