# Generated by Django 4.1 on 2024-06-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_caremployer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caremployer',
            old_name='id_type_car',
            new_name='id_car_type',
        ),
    ]
