# Generated by Django 4.1 on 2024-06-22 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_id_type_car_caremployer_id_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpayed',
            name='at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notify',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
