# Generated by Django 5.0.6 on 2024-06-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_id_type_car_caremployer_id_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
