# Generated by Django 4.1 on 2024-06-24 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_notify_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpayed',
            name='at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='isAbonner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_zaboun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.person')),
            ],
        ),
    ]
